#!/usr/bin/env php
<?php

$data = file_get_contents("./swagger.json"); // openapi 生成的 json 地址
$data = json_decode($data, true);

// 将 swagger 生成的标准文档处理成 swagger-bootstrap-ui 使用的文档

// 提取 tags
$tags = [];
foreach ($data['paths'] as $pkey => &$url) {
    $subs = explode("/", $pkey);
    $sub  = array_pop($subs);
    foreach ($url as $mkey => &$method) {
        $tags[] = $method['tags'][0];

        // 添加、去掉一些必要的属性
        $method['operationId'] = $sub . "Using" . strtoupper($mkey);
        foreach ($method['responses'] as $rkey => &$resp) {
            if (isset($resp['content']) && isset($resp['content']['application/json'])) {
                $resp = $resp['content']['application/json'];
                unset($resp['content']);
            }
        }
    }
}
$tags  = array_unique($tags);
$ntags = [];
foreach ($tags as $tag) {
    $ntags[] = ['name' => $tag, 'description' => ''];
}
$data['tags'] = $ntags;

$data['definitions'] = $data['components']['schemas'];
unset($data['components']);

// 可以根据其他属性取不同的host，做到不同环境皆可用

$data['host'] = $data['servers'][0]['url'];
$data['basePath'] = "/";

$data['consumes'] = "application/json";
$data['produces'] = "application/json";

$json = json_encode($data, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

$json = str_replace("components/schemas", "definitions", $json);

file_put_contents("./swagger/json/swagger1.json", $json);// swagger-bootstrap-ui 使用的json地址